### ISSUE TITLE
Allow gettting parse result when using `compile`

### ISSUE THREAD

**Issue by ctron** [freestrings/jsonpath#61]
Currently the `compile` function returns `impl FnMut(&Value) -> Result<Vec<&Value>, JsonPathError>`. And the error of the parsing process is only evaluated when the function is called, typically when you select for data.

However, to me it would make sense to return `ParseResult<impl FnMut(&Value) -> Result<Vec<&Value>, JsonPathError>>` instead and simplify the actual implementation, dropping the "match" that is re-executed every time.

I would also do this myself, in a custom function. However the Parser is marked to be made private:

~~~
pub use parser::Parser; // TODO private
~~~

If that helps, I could create a PR to add new `compile` function which implements the suggested approach.

**Comment by ctron** [comment]
On a second thought, it might be more helpful to actually make Parser, Node, … public.

That would also allow one to clone a parsed path.

**Comment by freestrings** [comment]
Thank you for your interest. I am not familiar with English, so I am not sure if the communication will work well.

 `Parser` was initially public, but now I intend to keep it for internal use of the module. I want to add a function to `Parser` because it is a personal project and it is being delayed.

As you say, now `compile` is re-executed every time. Any suggestions for a new approach would be greatly appreciated.

**Comment by ctron** [comment]
Thank you for the time to look into this. I am also not a native speaker.

I created a new PR #63 … which keeps the parser internal, but provides an API to re-use compiled expressions.

I wasn't able to model this API as a simple function that gets returned, but I think the `select` function isn't too bad.

**Comment by freestrings** [comment]
PR #63 Thank you very much.

`Compiled::compile` and the existing `compile` appear to be the same behavior.

```rust
pub fn compile(path: &str) -> impl FnMut(&Value) -> Result<Vec<&Value>, JsonPathError> {
    let node = parser::Parser::compile(path); // step 1.
    move |json| match &node {// step 2.
        Ok(node) => {
            let mut selector = Selector::default();
            selector.compiled_path(node).value(json).select()
        }
        Err(e) => Err(JsonPathError::Path(e.to_string())),
    }
}
```

The `node` compiled once in `step 1` is not recompiled.

For example,
```
let get_all_foo = compile("$..foo")
let r1 = get_all_foo(json!( .. ))
let r2 = get_all_foo(json!( .. ))
```
Because `get_all_foo` is a closure function, it reuses the compiled `node`. So the logic is the same as `Compiled::compile`.

And in the reply I wrote above, `As you say, now compile is re-executed every time` means that `step 2` is re-executed every time. (I'm sorry, I wasn't good at expressing it)

If there is any part I misunderstood your code, please comment.

**Comment by ctron** [comment]
You are right, sorry for the confusion. What I meant was: doesn't get re-evaluated.

Currently the outcome of the compilation process is not getting evaluated after the call to `parser::Parser::compile(path);` (step 1). The function returns a `Fn`, but no indication if the parsing was successful. So it may be, that the expression was wrong, and the returned function could ever produce a successful outcome.

Also will the result be re-evaluated every time the Fn/closure is called.

The change I made does evaluate the outcome of the parser. As you said, in a successful compilation, the expression will not be re-parsed, but still the result would be re-evaluated. With the change, the outcome will only be evaluated once, the caller will know that the expression was syntactically correct (or not) and the closure does not need to re-evaluate the parse result.

**Comment by freestrings** [comment]
Sorry for the late reply.

I understood your code. It seems to be a good direction. The PR will be merged and the new version will be released soon after some tests.

Thank you very much.

**Comment by ctron** [comment]
No worries :) Thank you for your time, and taking a look at the issue. I look forward to the release.
